### ISSUE TITLE
Servers not connecting to database and minor modifications to project wiki

### ISSUE THREAD

**Issue by rohankasture** [airavata-courses/Envy#35]
- It would be better if you write the exact commands to install. Referencing the  installation links is always good but it should also have commands to ease the installation process.
For develop_cheapest_service you could write "pip install djangorestframework" and "pip install django"

- You can have a requirements file to install all the project dependencies.

- Update the wiki. Some project dependencies are not mentioned in the wiki for windows
  1. corsheaders
  2. psycopg2

 Servers are not connecting to database(Not able to login or search locations)

**Comment by alakhsingh** [comment]
@rohankasture I have updated the wiki. There was an error with the db which was causing all the microservices to not start. We have fixed the issue. Please read the updated wiki page and try again.

**Comment by rohankasture** [comment]
I am still getting following issue while login
![image](https://user-images.githubusercontent.com/33710140/52529856-193cb100-2cc8-11e9-9d95-953aa49fee81.png)

**Comment by alakhsingh** [comment]
Hi @rohankasture , I don't think your DB is configured. Please follow the updated wiki commands and let me know

**Comment by rohankasture** [comment]
I have tested the application and it works fine. Overall I must say a great concept for the project. It would have been great if there was a single develop or release branch and the absence of which causes an issue requiring me to maintain a separate copy of each branch in order to run all micro-processes and even check all commits. Just make sure that wiki covers installation and execution steps with respect to both Unix and Windows-based systems.
